sudo: required
dist: trusty
language: php

php:
  - 7.1.18

branches:
 only:
   - master

before_script:
  - composer self-update
  - composer clear-cache -vvv
  - composer install --no-interaction -vvv
  - composer dump-autoload -vvv

script:
  - ./vendor/bin/phpunit --no-coverage --stop-on-error --stop-on-fail --no-coverage

